# Generated by Django 4.2.7 on 2024-05-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mailing_e_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
