# Generated by Django 4.2.7 on 2024-05-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='В обработке', max_length=50, verbose_name='Статус товара'),
        ),
    ]
